// Package routes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package routes

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Amount The amount to issue, transfer or redeem.
type Amount struct {
	// Code the code of the token
	Code string `json:"code"`

	// Value value in base units (usually cents)
	Value int64 `json:"value"`
}

// Counterparty The counterparty in a Transfer or Issuance transaction.
type Counterparty struct {
	Account string `json:"account"`

	// Node The node that holds the recipient account
	Node string `json:"node"`
}

// Error defines model for Error.
type Error struct {
	// Message High level error message
	Message string `json:"message"`

	// Payload Details about the error
	Payload string `json:"payload"`
}

// TransferRequest Instructions to issue or transfer tokens to an account
type TransferRequest struct {
	// Amount The amount to issue, transfer or redeem.
	Amount Amount `json:"amount"`

	// Counterparty The counterparty in a Transfer or Issuance transaction.
	Counterparty Counterparty `json:"counterparty"`

	// Message optional message that will be sent and stored with the transfer transaction
	Message *string `json:"message,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = Error

// HealthSuccess defines model for HealthSuccess.
type HealthSuccess struct {
	// Message ok
	Message string `json:"message"`
}

// IssuanceHistorySuccess defines model for IssuanceHistorySuccess.
type IssuanceHistorySuccess struct {
	Message string   `json:"message"`
	Payload []string `json:"payload"`
}

// IssueSuccess defines model for IssueSuccess.
type IssueSuccess struct {
	Message string `json:"message"`

	// Payload Transaction id
	Payload string `json:"payload"`
}

// IssueJSONRequestBody defines body for Issue for application/json ContentType.
type IssueJSONRequestBody = TransferRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Returns 200 if the service is healthy
	// (GET /healthz)
	Healthz(ctx echo.Context) error
	// Get all historical issuance
	// (GET /issuer/history)
	IssuerHistory(ctx echo.Context) error
	// Issue tokens of any kind to an account
	// (POST /issuer/issue)
	Issue(ctx echo.Context) error
	// Returns 200 if the service is ready to accept calls
	// (GET /readyz)
	Readyz(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Healthz converts echo context to params.
func (w *ServerInterfaceWrapper) Healthz(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Healthz(ctx)
	return err
}

// IssuerHistory converts echo context to params.
func (w *ServerInterfaceWrapper) IssuerHistory(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.IssuerHistory(ctx)
	return err
}

// Issue converts echo context to params.
func (w *ServerInterfaceWrapper) Issue(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Issue(ctx)
	return err
}

// Readyz converts echo context to params.
func (w *ServerInterfaceWrapper) Readyz(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Readyz(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/healthz", wrapper.Healthz)
	router.GET(baseURL+"/issuer/history", wrapper.IssuerHistory)
	router.POST(baseURL+"/issuer/issue", wrapper.Issue)
	router.GET(baseURL+"/readyz", wrapper.Readyz)

}

type ErrorResponseJSONResponse Error

type HealthSuccessJSONResponse struct {
	// Message ok
	Message string `json:"message"`
}

type IssuanceHistorySuccessJSONResponse struct {
	Message string   `json:"message"`
	Payload []string `json:"payload"`
}

type IssueSuccessJSONResponse struct {
	Message string `json:"message"`

	// Payload Transaction id
	Payload string `json:"payload"`
}

type HealthzRequestObject struct {
}

type HealthzResponseObject interface {
	VisitHealthzResponse(w http.ResponseWriter) error
}

type Healthz200JSONResponse struct{ HealthSuccessJSONResponse }

func (response Healthz200JSONResponse) VisitHealthzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Healthz503JSONResponse struct{ ErrorResponseJSONResponse }

func (response Healthz503JSONResponse) VisitHealthzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type IssuerHistoryRequestObject struct {
}

type IssuerHistoryResponseObject interface {
	VisitIssuerHistoryResponse(w http.ResponseWriter) error
}

type IssuerHistory200JSONResponse struct {
	IssuanceHistorySuccessJSONResponse
}

func (response IssuerHistory200JSONResponse) VisitIssuerHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type IssuerHistorydefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response IssuerHistorydefaultJSONResponse) VisitIssuerHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type IssueRequestObject struct {
	Body *IssueJSONRequestBody
}

type IssueResponseObject interface {
	VisitIssueResponse(w http.ResponseWriter) error
}

type Issue200JSONResponse struct{ IssueSuccessJSONResponse }

func (response Issue200JSONResponse) VisitIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type IssuedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response IssuedefaultJSONResponse) VisitIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ReadyzRequestObject struct {
}

type ReadyzResponseObject interface {
	VisitReadyzResponse(w http.ResponseWriter) error
}

type Readyz200JSONResponse struct{ HealthSuccessJSONResponse }

func (response Readyz200JSONResponse) VisitReadyzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Readyz503JSONResponse struct{ ErrorResponseJSONResponse }

func (response Readyz503JSONResponse) VisitReadyzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Returns 200 if the service is healthy
	// (GET /healthz)
	Healthz(ctx context.Context, request HealthzRequestObject) (HealthzResponseObject, error)
	// Get all historical issuance
	// (GET /issuer/history)
	IssuerHistory(ctx context.Context, request IssuerHistoryRequestObject) (IssuerHistoryResponseObject, error)
	// Issue tokens of any kind to an account
	// (POST /issuer/issue)
	Issue(ctx context.Context, request IssueRequestObject) (IssueResponseObject, error)
	// Returns 200 if the service is ready to accept calls
	// (GET /readyz)
	Readyz(ctx context.Context, request ReadyzRequestObject) (ReadyzResponseObject, error)
}

type StrictHandlerFunc = runtime.StrictEchoHandlerFunc
type StrictMiddlewareFunc = runtime.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Healthz operation middleware
func (sh *strictHandler) Healthz(ctx echo.Context) error {
	var request HealthzRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Healthz(ctx.Request().Context(), request.(HealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(HealthzResponseObject); ok {
		return validResponse.VisitHealthzResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// IssuerHistory operation middleware
func (sh *strictHandler) IssuerHistory(ctx echo.Context) error {
	var request IssuerHistoryRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.IssuerHistory(ctx.Request().Context(), request.(IssuerHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IssuerHistory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(IssuerHistoryResponseObject); ok {
		return validResponse.VisitIssuerHistoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// Issue operation middleware
func (sh *strictHandler) Issue(ctx echo.Context) error {
	var request IssueRequestObject

	var body IssueJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Issue(ctx.Request().Context(), request.(IssueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Issue")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(IssueResponseObject); ok {
		return validResponse.VisitIssueResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// Readyz operation middleware
func (sh *strictHandler) Readyz(ctx echo.Context) error {
	var request ReadyzRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Readyz(ctx.Request().Context(), request.(ReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Readyz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ReadyzResponseObject); ok {
		return validResponse.VisitReadyzResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RYW2/bNhT+KwfcHlqAsJymGzC/tVuxBHsp0gwb1uSBpo4tNhSpkpQzLdB/H3iRZNmy",
	"06TBlj5F5uVcvvOdC3NHuC4rrVA5SxZ3xKCttLIYfrwzRpuLtOIXuFYOlfOfrKqk4MwJrbJPViu/ZnmB",
	"JfNf3xtckQX5LhukZ3HXZkEqaduWkhwtN6LyQsgiqoPOAtJScoZMuuJDzTla+yAD8G9WVjIYXaK1bI1k",
	"QfSNF1oZXaFxIvrY797tWKNvCCWuqfxF64xQa+JNNvi5FgZzsvjY373uD+rlJ+RuyrnkxMi9c2trpjie",
	"Ceu0aR7j50FnegCISFqgiGrAoDMCN5jvO0hJxRqpWe5FCIel3Qfm0jBlGfe/QEzKSAvMGNYcBG1Q9TXw",
	"4ZOCdgyNh4HwpE5rA7iTGy1N/gQX3pS6jo7vWFkgsLAHToMnAlJw3vQVGggCc8RyRuh2wnCde7ve/X7x",
	"J6Fkw2SNZHEyn+/lTjzola5YLd1wZ2yFKxD8UdAr8N9O36Ca4k1StetFWAahYMksQq2Es/CitjWTsgHu",
	"a8tLQslKm5J5G4RyP74mlJRCibIuyWLeqxLK4RrNXniCI53+/chQ8rPHEE3FjGumYeZbJ7ytDC63cO4y",
	"PYIfebODOuM8BpEwKbg3R8U46FuF5mS/cvUXJnir+sjs2ul3wBXMQaFlbkNADHJRCVQOOpn38VlFwLrj",
	"U5DFMn+oFEc+76fFgjygRJ+JdQESNyhhV96XZ/Iv6JiQFthS1y7AEWQ9SUpT0pHgAj/XaCdS9FxZZ+pA",
	"CNsnqadMn6YhXcIeU1sB2iFDXwGOtd5UJ1pK+A6hj90akb+lR1pm+GCyi0Pk2a2QEpYINhBM5eC7EOZw",
	"K1wR60Hv6ZAc98I/coB2/k9XVaFWegL5WA59GmwVRW9grIoJ+Bm8ZfwGc1g2wCAX3p5l7TAHifkaDb1S",
	"lUGLZiPUGiojNow3UFv/6y80Gn5T+jYchfdG65WdwWUhLLx5fw45roQSoYmsjFbOwmvIxWqFxmMVZHK0",
	"FG4LwQtAxguoJIt2pFNXymgZqmOgLte2sQ7L2ZW6UpcanGlAONC1oyAx8js4bhLTrC4RVrXKA8O06qt0",
	"bdHYGfzBHI9hWjLpS5i9Umt0UFc58yCEgCIOgUxNMQ0bs6EMChc5rF3hcY5EpkMXulJ9cwi25Gid0Y2X",
	"HDqUEy7MM5fhhC/XaGwM5cls7ompK1SsEmRBTmfz2WlITVeE/MhYnQunTZb02uxO5G0YC9B4QWTxcZcg",
	"6QqhpDaSLEjhXLXIMqk5k4W2bvHTfD7PWCWyzUlG2uuWHlCTbQFjn15nEabkf7zgNYYa4CtDGH7OfUU9",
	"S/t0PN2/ms8PZX5/LhtP4C0lP8xP7781fjiEYaUuS2YasiAX6GqjLLyaz0FEqiWig7AQffEZ7djaAzT4",
	"Ysm1l5QF3posEeyg15HlabR+lO8HxvMwpqWB5xFAHAx99OtI5E9Gkd/G9Fd0wKRMSSc4k9BN/VtIJgXX",
	"/4cVW4ELf8IYru2huJFY7NG6tzpvnuzpuduNJ2bu6X7cF8hRCx76kTM1to/lGD5jZgX7uqKsV8BUAzdC",
	"5XtY/FckGxk0NsJzLAzLffW9p9b6OTs0sKVeHjHm1bYxdFcKZ0ZqG8TkTB0Rc7pXuMfGfklHeoYWZ7F7",
	"P2PDx90njHYvlrVRLxONyCHPHtC2n2Ngupn2GwnN5dSDZzQshkAZZHlzeNi5iNvfwqwTPAluco6VA86k",
	"tAcnn6MF9YFjI/26gkyfGYcSYPvyFHCDzE01MJpeLr6VFeGxByGHoO8dlChW4gDOFGqjkKb/qlgXl2+w",
	"ic50Er16ry+8rAbxQe2E9DW6kAT+dYUbNM3ofZUefFwiM9GXG8TKAuteXoOCjhz7Kj4ky+PUnd6+LBfK",
	"J8Bg4MDD9rr9NwAA//9AJPs7MhgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
